name: aada_appv2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  dio: ^5.3.4
# firebase_messaging: ^14.7.9  # Temporarily disabled for testing
  intl: ^0.18.0
  path_provider: ^2.1.1
  path: ^1.8.3
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/aada_logo_login.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/aada_logo_login.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/aada_logo_login.png"
    background_color: "#FFFFFF"
    theme_color: "#FFC107"
  macos:
    generate: true
    image_path: "assets/images/aada_logo_login.png"
